### ISSUE TITLE
Question abouthe offset in `preprocess_elect.py` function - is this an error?

### ISSUE THREAD

**Issue by 00krishna** [zhykoties/DeepAR#10]
Hello. Thanks so much for creating this repository. I was going through the preprocessing code, and it 
seems like there is an error in the code. But I wanted to check with you, in case I was just misinterpreting it. 

So in the `preprocess_elect.py` module, in the `prep_data()` function there is a set of [lines](https://github.com/zhykoties/TimeSeries/blob/b12b13c8250a096e38882d258213abd6c2d78c43/preprocess_elect.py#L65) like:

```
            x_input[count, 1:, 0] = data[window_start:window_end-1, series]  # <--- QUESTION
            x_input[count, :, 1:1+num_covariates] = covariates[window_start:window_end, :]
            x_input[count, :, -1] = series
```
The problem is that the `x_input[count, 1:, 0]` begins at index 1 instead of 0. So that will actually make the window size 191 instead of 192. And it is not clear what the benefit of starting every window with 0 will be. But further, the other arrays, such as `labels` goes from `window_start` to `window_end`. If that is the case, then the `x_input` array and the `labels` array is off by an increment. 

So I was not sure which is the right way to do it, or whether this is written accurately. Would you mind clarifying if you have a chance. Thanks.

**Comment by zhykoties** [comment]
Hi, that is the correct setting for DeepAR and some other autoregressive models. At every time step, z_t is given and the goal is to predict z_{t+1}. In this way, if the window size is 192, we actually need 193 timesteps to cover both given and labels. Therefore, we let the first timestep in the window be 0. There are other setups too. See Figure 2 of the DeepAR paper for details.

**Comment by 00krishna** [comment]
@zhykoties Okay, that helps a lot. Thanks so much. Now I understand what you were looking to do. Thanks again.
