### ISSUE TITLE
possible bug in preprocessing script related to calculation of z-score (normalization of data)

### ISSUE THREAD

**Issue by super-shayan** [zhykoties/DeepAR#12]
hello, why is it that v_input is initialized with 2 columns (mean and std i presume) but only one of them is changed. It also looks strange that instead of subtracting the mean, the series is divided by the mean as in the following lines: 

```
v_input[count, 0] = np.true_divide(x_input[count, 1:input_size, 0].sum(),nonzero_sum)+1
x_input[count, :, 0] = x_input[count, :, 0]/v_input[count, 0]
```

**Comment by zhykoties** [comment]
v[:, 1] is not used. Only v[:, 0] is used. See Section 3.3 in https://arxiv.org/pdf/1704.04110.pdf.
