### ISSUE TITLE
Elaboration on the results.

### ISSUE THREAD

**Issue by padmaksha18** [zhykoties/DeepAR#13]
@zhykoties Hi there, I just wanted to understand the uncertainty estimation graph. Here, red line denotes the likelihood function and the blue denotes the actual ground truth data. In that case, the X-axis is the sample size of the data which is 200 here but I did not understand the Y-axis, what does the Y-axis represent exactly, will you please explain. Also, the values change in the Y-axis. Thanks!

**Comment by yyyyqy** [comment]
Also, I don't know what the physical meaning of the horizontal and vertical axes of the final output loss curve is, did you figure it out?

**Comment by zhykoties** [comment]
@padmaksha18 You can read the plots in the context of a time series. Given xxx steps, predict yyy steps ahead. 200 samples are used to construct the confidence interval on the plots, which is not the X-axis.
