### ISSUE TITLE
what is the `v`

### ISSUE THREAD

**Issue by FarhangAmaji** [zhykoties/DeepAR#17]
the `v` is used in `TestDataset` and `WeightedSampler` and also used in `evaluate` to rescale the mu and sigma
```
input_mu[:,t] = v_batch[:, 0] * mu + v_batch[:, 1]
input_sigma[:,t] = v_batch[:, 0] * sigma
```

**Comment by zhykoties** [comment]
v[:, 0] is the mean of each window, which is used to scale the window. v[:, 1] is not used and is kept as zeros.

See https://github.com/zhykoties/TimeSeries/blob/b12b13c8250a096e38882d258213abd6c2d78c43/preprocess_elect.py#L73
