### ISSUE TITLE
confusion in the net.test function ,line 87

### ISSUE THREAD

**Issue by hihihihiwsf** [zhykoties/DeepAR#2]
In the /model/net.py file, line 87, when the model do inference from [predict_start ,predict_start+ predict_step] , it can use the true information of them, which is not properly for model test. In the test stage, the model only input the true value of x[predict_start], and the  following step should input the last predict mu instead.

**Comment by zhykoties** [comment]
Thank you for your suggestion. If you look at line 93, we have replaced x[self.params.predict_start + t] with the last predicted mu, so it indeed does what you described.

**Comment by hihihihiwsf** [comment]
Thanks for your reply!
 I have another confusion about the evaluate function. I noticed that in the function 'train_and_evaluate,' after the training of each epoch, there is a evaluation without sampling. But during each epoch's training  in the 'train' function,  the evalution is with sampling but the test_metrics have not been used. What's the purpose of this evaluation and the difference about sampling or not (I tried to use sampling in the 'train_and_evaluation' function but get poorer result) ? I'd like to also make sure that is there anywhere else used the sampling including but not limited to evaluation function.

**Comment by zhykoties** [comment]
Sampling is not done during training and is only used for evaluation (inference). If you set sample_times in /experiments/base_model/params.json to a number that is big enough, the result should be similar to just parsing mu without sampling. The reason sampling is included is to calculate the confidence interval during inference.
