### ISSUE TITLE
I think I found mistakes

### ISSUE THREAD

**Issue by sjhan91** [zhykoties/DeepAR#4]
Hello, Thanks for your effort. I'm verifying your code.

In _model.test()_ in _net.py_, decoding part seems unnatural.

The task is to predict indices from 168 ~ 191 (24 time samples) using 0 ~ 167 samples (168 time samples). It is assumed that we do not know predicting part.

In your source, however, at iter 0, we already know 168 index from original data, and it occurred last time step to be discarded due to out of index.

I thinks it can be fixed like this:

```
for t in range(self.params.predict_steps):
   mu_de, sigma_de, decoder_hidden, decoder_cell = self(x[self.params.predict_start+(t-1)].unsqueeze(0), id_batch, decoder_hidden, decoder_cell)
   sample_mu[:, t] = mu_de * v_batch[:, 0] + v_batch[:, 1]
   sample_sigma[:, t] = sigma_de * v_batch[:, 0]
   x[self.params.predict_start+t, :, 0] = mu_de
```

**Comment by kaishxu** [comment]
> Hello, Thanks for your effort. I'm verifying your code.
> 
> In _model.test()_ in _net.py_, decoding part seems unnatural.
> 
> The task is to predict indices from 168 ~ 191 (24 time samples) using 0 ~ 167 samples (168 time samples). It is assumed that we do not know predicting part.
> 
> In your source, however, at iter 0, we already know 168 index from original data, and it occurred last time step to be discarded due to out of index.
> 
> I thinks it can be fixed like this:
> 
> ```
> for t in range(self.params.predict_steps):
>    mu_de, sigma_de, decoder_hidden, decoder_cell = self(x[self.params.predict_start+(t-1)].unsqueeze(0), id_batch, decoder_hidden, decoder_cell)
>    sample_mu[:, t] = mu_de * v_batch[:, 0] + v_batch[:, 1]
>    sample_sigma[:, t] = sigma_de * v_batch[:, 0]
>    x[self.params.predict_start+t, :, 0] = mu_de
> ```

hi, I have another question about the code. Do you notice that values of v_batch[:, 1] equal 0? and why sigma = sigma_de * v_batch[:,0], which is same as mu?

**Comment by sjhan91** [comment]
@KaishuaiXu Exactly you are right. I think you can discard v_batch[:, 1]. I checked v_batch[:, 1] is not used in whole code.

**Comment by kaishxu** [comment]
> Hello, Thanks for your effort. I'm verifying your code.
> 
> In _model.test()_ in _net.py_, decoding part seems unnatural.
> 
> The task is to predict indices from 168 ~ 191 (24 time samples) using 0 ~ 167 samples (168 time samples). It is assumed that we do not know predicting part.
> 
> In your source, however, at iter 0, we already know 168 index from original data, and it occurred last time step to be discarded due to out of index.
> 
> I thinks it can be fixed like this:
> 
> ```
> for t in range(self.params.predict_steps):
>    mu_de, sigma_de, decoder_hidden, decoder_cell = self(x[self.params.predict_start+(t-1)].unsqueeze(0), id_batch, decoder_hidden, decoder_cell)
>    sample_mu[:, t] = mu_de * v_batch[:, 0] + v_batch[:, 1]
>    sample_sigma[:, t] = sigma_de * v_batch[:, 0]
>    x[self.params.predict_start+t, :, 0] = mu_de
> ```

In my mind, since the logic of prediction is auto-regression, we should use the `mu` produced by the last step of encoder as the input of the first step of decoder. The code is as follows.
```test_batch[params.test_predict_start, :, 0] = input_mu[:, params.test_predict_start-1] / v_batch[:, 0]```
or
```test_batch[params.test_predict_start, :, 0] = mu```

This line should be put before the `model.test()` in evaluate.py like this.
```
for t in range(params.test_predict_start):  # encoder
    # if z_t is missing, replace it by output mu from the last time step
    zero_index = (test_batch[t,:,0] == 0)
    if t > 0 and torch.sum(zero_index) > 0:
        test_batch[t,zero_index,0] = mu[zero_index]

    mu, sigma, hidden, cell = model(test_batch[t].unsqueeze(0), id_batch, hidden, cell)
    input_mu[:,t] = v_batch[:, 0] * mu + v_batch[:, 1]  # v_batch[:, 1] == 0, useless
    input_sigma[:,t] = v_batch[:, 0] * sigma

test_batch[params.test_predict_start, :, 0] = input_mu[:, params.test_predict_start-1] / v_batch[:, 0]

# decoder
if sample:
    samples, sample_mu, sample_sigma = model.test(test_batch, v_batch, id_batch, hidden, cell, sampling=True)
    raw_metrics = utils.update_metrics(raw_metrics, input_mu, input_sigma, sample_mu, labels, params.test_predict_start, samples, relative = params.relative_metrics)
else:
    sample_mu, sample_sigma = model.test(test_batch, v_batch, id_batch, hidden, cell)
    raw_metrics = utils.update_metrics(raw_metrics, input_mu, input_sigma, sample_mu, labels, params.test_predict_start, relative = params.relative_metrics)
```

**Comment by zhykoties** [comment]
Very good points! I will fix them in the next update

If you want to subtract the mean value of the window, v_batch[:,1] will be non-zero.

**Comment by kaishxu** [comment]
> Very good points! I will fix them in the next update
> 
> If you want to subtract the mean value of the window, v_batch[:,1] will be non-zero.

Thanks a lot for your reply!
You can add the description of the v_batch[:, 1] in your code, since it is different from the published paper.

**Comment by kaishxu** [comment]
Hi, 
In net.py, the function Net.test() use torch.median() to compute the sample_mu when sampling=True. However, statistically, we use the sample mean rather than the sample median to replace a population mean.

**Comment by liuliuforph** [comment]
> Hello, Thanks for your effort. I'm verifying your code.
> 
> In _model.test()_ in _net.py_, decoding part seems unnatural.
> 
> The task is to predict indices from 168 ~ 191 (24 time samples) using 0 ~ 167 samples (168 time samples). It is assumed that we do not know predicting part.
> 
> In your source, however, at iter 0, we already know 168 index from original data, and it occurred last time step to be discarded due to out of index.
> 
> I thinks it can be fixed like this:
> 
> ```
> for t in range(self.params.predict_steps):
>    mu_de, sigma_de, decoder_hidden, decoder_cell = self(x[self.params.predict_start+(t-1)].unsqueeze(0), id_batch, decoder_hidden, decoder_cell)
>    sample_mu[:, t] = mu_de * v_batch[:, 0] + v_batch[:, 1]
>    sample_sigma[:, t] = sigma_de * v_batch[:, 0]
>    x[self.params.predict_start+t, :, 0] = mu_de
> ```

Since the definition of the input is the concatenation of Z_{t-1} and X_t, I don't think it's a mistake. Note that Z_0 = 0.
