### ISSUE TITLE
Some confusion about calculate distribution_mu&sigma

### ISSUE THREAD

**Issue by chenjw505** [zhykoties/DeepAR#7]
first，thanks for ur code！it‘s very helpful!
in your code， when your calculate the mu&sigma use the h from all three layers。
![image](https://user-images.githubusercontent.com/43956043/81669888-6d10e980-9479-11ea-939e-cca5911bb425.png)

but in the deepar paper calculate the mu&sigma use the h from the last layers 。 

![image](https://user-images.githubusercontent.com/43956043/81669920-7b5f0580-9479-11ea-984c-829704d25199.png)

which one is better？

**Comment by zhykoties** [comment]
I haven't compared, but I guess it should be straightforward to implement DeepAR's original architecture.
